/* Bundles the site into one self-contained HTML file for the Artifact preview.
   Inlines CSS, JS and images, and stubs the network with representative demo
   data (the preview sandbox can't reach DexScreener or the chain RPC). */
const fs = require('fs'), path = require('path');
const root = __dirname;
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8');

let html = read('index.html');
let css = read('assets/css/style.css');
const JS = ['config.js','keccak.js','app.js','market.js','wallet.js','swap.js','feed.js','arena.js','doge.js','buypop.js','room.js'];

// images -> data URIs (the preview sandbox can't load sibling files)
const MIME = { png:'image/png', webp:'image/webp', gif:'image/gif', ico:'image/x-icon' };
const dataUri = (p) => {
  const ext = p.split('.').pop();
  return `data:${MIME[ext]};base64,` +
    fs.readFileSync(path.join(root, p)).toString('base64');
};
// The GIF is only a fallback for browsers without animated WebP; the preview
// runs in one that has it, so inlining both would just double the payload.
html = html.replaceAll('assets/img/robin-doge.gif', 'assets/img/robin-doge.webp');
const IMG = [
  'robin-logo.png','robin-logo.webp','robin-logo-128.png','robin-logo-128.webp',
  'robin-doge.webp','robin-doge-poster.webp','grain.png',
  'favicon-32.png','favicon-48.png','favicon.ico','apple-touch-icon.png',
];
const LOGO = dataUri('assets/img/robin-logo.png');
for (const f of IMG) html = html.replaceAll('assets/img/' + f, dataUri('assets/img/' + f));
// The stylesheet reaches images by its own relative path, which stops meaning
// anything once it is inlined into the document.
css = css.replaceAll('../img/grain.png', dataUri('assets/img/grain.png'));

// The artwork wordmark is optional: without it the page falls back to the
// drawn lettering, and the preview should show whichever the real site would.
const WORDMARK = 'assets/img/robin-wordmark.png';
if (fs.existsSync(path.join(root, WORDMARK))) {
  const uri = dataUri(WORDMARK);
  html = html.replaceAll(WORDMARK, uri);
  css = css.replaceAll('../img/robin-wordmark.png', uri);
} else {
  // No file, so take the <img> out altogether and start on the drawn wordmark.
  // Leaving the tag in would have the preview reach for a file that is not
  // there, which is exactly what this build is supposed to avoid.
  html = html.replace('class="wordmark enter enter-3"', 'class="wordmark wm-drawn enter enter-3"')
             .replace(/\s*<img class="wm-img"[\s\S]*?>\s*/, '\n          ');
}

// keep only what lives inside <body>, plus the title
const title = 'Robin Nakamoto';   // gallery name; the shipped site keeps its SEO title
let body = html.slice(html.indexOf('<body>') + 6, html.indexOf('</body>'));
body = body.replace(/<script src="assets\/js\/[^"]+"><\/script>\s*/g, '');

const fontLink = html.match(/<link href="https:\/\/fonts\.googleapis[^>]+>/)[0];

const demo = fs.readFileSync(path.join(root, 'test/demo-shim.js'), 'utf8');

const demoBadge = `
<style>
  /* The shim sets this attribute only when a real request actually failed, so
     a preview that can reach the network shows nothing at all. */
  #demoBadge{display:none}
  html[data-preview-sample] #demoBadge{display:flex}
</style>
<div id="demoBadge" style="
  position:fixed;left:50%;transform:translateX(-50%);bottom:12px;z-index:400;
  align-items:center;gap:8px;padding:9px 16px;border-radius:999px;
  background:rgba(8,11,5,.9);color:#ffd447;border:1px solid rgba(255,212,71,.35);
  font:600 12px/1 Inter,system-ui,sans-serif;letter-spacing:.02em;
  backdrop-filter:blur(14px);-webkit-backdrop-filter:blur(14px);
  box-shadow:0 12px 34px -14px rgba(0,0,0,.9);pointer-events:none;">
  <span style="width:7px;height:7px;border-radius:50%;background:#ffd447;flex:none"></span>
  PREVIEW SANDBOX — live APIs blocked, showing samples
</div>`;

const banner =
`<!-- $ROBIN — Robin Nakamoto · preview build
     Generated from index.html + assets/. Do not edit this file; edit the
     sources and re-run: node build-preview.js -->`;

const out = [
  banner,
  `<title>${title}</title>`,
  fontLink,
  `<style>\n${css}\n</style>`,
  body.trim(),
  demoBadge,
  `<script>${demo}</script>`,
  ...JS.map((f) => `<script>\n${read('assets/js/' + f)
      .replaceAll('assets/img/robin-logo-128.png', LOGO)
      .replaceAll('assets/img/robin-logo.png', LOGO)}\n</script>`),
].join('\n');

const dest = process.argv[2] || path.join(root, 'preview.html');
fs.writeFileSync(dest, out);
console.log(`preview -> ${dest}  (${(out.length / 1024).toFixed(0)} KB)`);
