/* Bundles the site into one self-contained HTML file for the Artifact preview.
   Inlines CSS, JS and images, and stubs the network with representative demo
   data (the preview sandbox can't reach DexScreener or the chain RPC). */
const fs = require('fs'), path = require('path');
const root = __dirname;
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8');

let html = read('index.html');
const css = read('assets/css/style.css');
const JS = ['config.js','keccak.js','app.js','market.js','wallet.js','swap.js','feed.js','ai.js','doge.js'];

// images -> data URIs (the preview sandbox can't load sibling files)
const MIME = { png:'image/png', webp:'image/webp', gif:'image/gif', ico:'image/x-icon' };
const dataUri = (p) => {
  const ext = p.split('.').pop();
  return `data:${MIME[ext]};base64,` +
    fs.readFileSync(path.join(root, p)).toString('base64');
};
// The GIF is only a fallback for browsers without animated WebP; the preview
// runs in one that has it, so inlining both would just double the payload.
html = html.replaceAll('assets/img/robin-doge.gif', 'assets/img/robin-doge.webp');
const IMG = [
  'robin-logo.png','robin-logo.webp','robin-logo-128.png','robin-logo-128.webp',
  'robin-doge.webp','robin-doge-poster.webp',
  'favicon-32.png','favicon-48.png','favicon.ico','apple-touch-icon.png',
];
const LOGO = dataUri('assets/img/robin-logo.png');
for (const f of IMG) html = html.replaceAll('assets/img/' + f, dataUri('assets/img/' + f));

// keep only what lives inside <body>, plus the title
const title = 'Robin Nakamoto';   // gallery name; the shipped site keeps its SEO title
let body = html.slice(html.indexOf('<body>') + 6, html.indexOf('</body>'));
body = body.replace(/<script src="assets\/js\/[^"]+"><\/script>\s*/g, '');

const fontLink = html.match(/<link href="https:\/\/fonts\.googleapis[^>]+>/)[0];

const demo = fs.readFileSync(path.join(root, 'test/demo-shim.js'), 'utf8');

const banner =
`<!-- $ROBIN — Robin Nakamoto · preview build
     Generated from index.html + assets/. Do not edit this file; edit the
     sources and re-run: node build-preview.js -->`;

const out = [
  banner,
  `<title>${title}</title>`,
  fontLink,
  `<style>\n${css}\n</style>`,
  body.trim(),
  `<script>${demo}</script>`,
  ...JS.map((f) => `<script>\n${read('assets/js/' + f)
      .replaceAll('assets/img/robin-logo-128.png', LOGO)
      .replaceAll('assets/img/robin-logo.png', LOGO)}\n</script>`),
].join('\n');

const dest = process.argv[2] || path.join(root, 'preview.html');
fs.writeFileSync(dest, out);
console.log(`preview -> ${dest}  (${(out.length / 1024).toFixed(0)} KB)`);
